# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pedro Pineda
email: contacto@lamuina.com
description: > # this means to ignore newlines until "baseurl:"
  ¡Bienvenido a mi sitio web personal!
  Sigueme en twitter para enterarte de actualizaciones.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lamuina.com" # the base hostname & protocol for your site
twitter_username: pedro55324574
github_username:  pedropda

# Build settings
markdown: kramdown
